In [ ]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [ ]:
iris = datasets.load_iris()

In [ ]:
idf = pd.DataFrame(iris.data, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

In [ ]:
idf['target'] = iris.target

In [ ]:
idf.head()

In [ ]:
Y = idf['target']

In [ ]:
X = idf[['sepal_length', 'sepal_width']]

In [ ]:
print X.shape
print Y.shape

In [ ]:
# ascceomg other data formats
blah = pd.DataFrame({'Col1' : range(5), 'Col2' : [1.0]*5, 'Col3' : 1.0, 'Col4' : 'Hello World!'})
blah

In [ ]:
blah.dtypes

In [ ]:
# changing the format
blah['Col1'] = blah['Col1'].astype(float)

In [ ]:
blah.dtypes

In [ ]:
# data preprocssing
# mask features to select columns

mask_feature = idf['sepal_length'] > 6.0

print mask_feature[0:4]

In [ ]:
len(idf[mask_feature]), len(idf)

In [ ]:
mask_target = idf['target'] == 2

In [ ]:
# select on those that are virginac in the data with a mask
idf.loc[mask_target, 'target'].head()

In [ ]:
# using unique 
idf.target.unique()

In [ ]:
idf.groupby('target').var()

In [ ]:
# sorting example
idf.sort_index(by = 'sepal_width').head()

In [ ]:
# using index to access valuesw

print float(idf.ix[104, 2])
print float(idf.ix[104, 'petal_length'])

In [ ]:
# retriving submatrices
idf[['sepal_length', 'sepal_width']][0:2]

In [ ]:
# or it can be ran as
print idf.loc[range(100,102), ['sepal_length', 'sepal_width']]
print idf.ix[range(100, 102), [0,1]]
print idf.iloc[range(100,102), [0,1]]

In [ ]:
# making dummies in pandas
level = ['sunny', 'cloudy', 'snowy', 'rainy', 'foggy']

cat_feat = pd.Series(level)
mapping = pd.get_dummies(cat_feat)
mapping

In [ ]:
# the same operation can be done with scikit learn
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
ohe = OneHotEncoder()
fit_levs = le.fit_transform(level)

In [ ]:
ohe.fit([[fit_levs[0]], [fit_levs[1]], [fit_levs[2]], [fit_levs[3]], 
[fit_levs[4]]])

In [ ]:
print ohe.transform([le.transform(['sunny'])]).toarray()
print ohe.transform([le.transform(['cloudy'])]).toarray()

In [29]:
# handling text data
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_20newsgroups
categories = ['sci.med', 'sci.space']
twenty_sci_news = fetch_20newsgroups(categories=categories)

In [30]:
twenty_sci_news.data[0]

u'From: flb@flb.optiplan.fi ("F.Baube[tm]")\nSubject: Vandalizing the sky\nX-Added: Forwarded by Space Digest\nOrganization: [via International Space University]\nOriginal-Sender: isu@VACATION.VENARI.CS.CMU.EDU\nDistribution: sci\nLines: 12\n\nFrom: "Phil G. Fraering" <pgf@srl03.cacs.usl.edu>\n> \n> Finally: this isn\'t the Bronze Age, [..]\n> please try to remember that there are more human activities than\n> those practiced by the Warrior Caste, the Farming Caste, and the\n> Priesthood.\n\nRight, the Profiting Caste is blessed by God, and may \n freely blare its presence in the evening twilight ..\n\n-- \n* Fred Baube (tm)\n'

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
word_count = count_vect.fit_transform(twenty_sci_news.data)
word_count.shape

(1187, 25638)

In [32]:
print word_count[0]

  (0, 10827)	2
  (0, 10501)	2
  (0, 17170)	1
  (0, 10341)	1
  (0, 4762)	2
  (0, 23381)	2
  (0, 22345)	1
  (0, 24461)	1
  (0, 23137)	7
  (0, 21382)	1
  (0, 3233)	1
  (0, 10713)	1
  (0, 5650)	3
  (0, 21686)	2
  (0, 8438)	1
  (0, 17217)	1
  (0, 24626)	1
  (0, 13158)	1
  (0, 24151)	1
  (0, 17235)	1
  (0, 20909)	1
  (0, 13359)	1
  (0, 24415)	1
  (0, 24547)	1
  (0, 7646)	1
  :	:
  (0, 15968)	1
  (0, 12362)	1
  (0, 3191)	1
  (0, 23129)	1
  (0, 23241)	1
  (0, 18474)	1
  (0, 24930)	1
  (0, 6017)	3
  (0, 10188)	1
  (0, 3808)	2
  (0, 18642)	1
  (0, 20110)	1
  (0, 18744)	1
  (0, 13318)	1
  (0, 5148)	1
  (0, 11330)	1
  (0, 15246)	1
  (0, 10785)	1
  (0, 5134)	1
  (0, 13384)	1
  (0, 18586)	1
  (0, 12716)	1
  (0, 9796)	1
  (0, 23849)	1
  (0, 10778)	1


In [33]:
# see direct correspondecen to words
word_list  = count_vect.get_feature_names()
for n in word_count[0].indices:
    print "Word:", word_list[n], "appears", word_count[0,n], "times"

Word: from appears 2 times
Word: flb appears 2 times
Word: optiplan appears 1 times
Word: fi appears 1 times
Word: baube appears 2 times
Word: tm appears 2 times
Word: subject appears 1 times
Word: vandalizing appears 1 times
Word: the appears 7 times
Word: sky appears 1 times
Word: added appears 1 times
Word: forwarded appears 1 times
Word: by appears 3 times
Word: space appears 2 times
Word: digest appears 1 times
Word: organization appears 1 times
Word: via appears 1 times
Word: international appears 1 times
Word: university appears 1 times
Word: original appears 1 times
Word: sender appears 1 times
Word: isu appears 1 times
Word: vacation appears 1 times
Word: venari appears 1 times
Word: cs appears 1 times
Word: cmu appears 1 times
Word: edu appears 2 times
Word: distribution appears 1 times
Word: sci appears 1 times
Word: lines appears 1 times
Word: 12 appears 1 times
Word: phil appears 1 times
Word: fraering appears 1 times
Word: pgf appears 1 times
Word: srl03 appears 1 times
W

In [34]:
# compute word frequency with Tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vect = TfidfVectorizer(use_idf = False, norm='l1' )
word_freq = tf_vect.fit_transform(twenty_sci_news.data)
word_list = tf_vect.get_feature_names()
for n in word_freq[0].indices :
    print "Word : ", word_list[n], "has frequency", word_freq[0, n]

Word :  from has frequency 0.021978021978
Word :  flb has frequency 0.021978021978
Word :  optiplan has frequency 0.010989010989
Word :  fi has frequency 0.010989010989
Word :  baube has frequency 0.021978021978
Word :  tm has frequency 0.021978021978
Word :  subject has frequency 0.010989010989
Word :  vandalizing has frequency 0.010989010989
Word :  the has frequency 0.0769230769231
Word :  sky has frequency 0.010989010989
Word :  added has frequency 0.010989010989
Word :  forwarded has frequency 0.010989010989
Word :  by has frequency 0.032967032967
Word :  space has frequency 0.021978021978
Word :  digest has frequency 0.010989010989
Word :  organization has frequency 0.010989010989
Word :  via has frequency 0.010989010989
Word :  international has frequency 0.010989010989
Word :  university has frequency 0.010989010989
Word :  original has frequency 0.010989010989
Word :  sender has frequency 0.010989010989
Word :  isu has frequency 0.010989010989
Word :  vacation has frequency 0.

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer() # tfidf true
word_tfidf = tfidf_vect.fit_transform(twenty_sci_news.data)
word_list = tfidf_vect.get_feature_names()

In [43]:
words = []
scores = []

for n in word_tfidf[0].indices:
    #print "Word :", word_list[n], "has tfidf", word_tfidf[0, n]
    words.append(word_list[n])
    scores.append(word_tfidf[0, n])

In [56]:
words_scores = pd.DataFrame(np.column_stack((words, scores)))
words_scores.columns = ['words','score']

In [59]:
print "Top 5 words"
print words_scores.sort('score', ascending=False).head(5)

Top 5 words
    words           score
17  caste   0.43258869397
72    flb   0.26428200052
69  baube   0.26428200052
68     tm  0.219051510033
65    the  0.157543062907


In [65]:
# taking a pair of words together using bigrams
text_1 = 'we love data science'
text_2 = 'data science is hard'
documents = [text_1, text_2]
documents

['we love data science', 'data science is hard']

In [69]:
# this is without bigrams
count_vec_1_grams = CountVectorizer(ngram_range=(1,1), stop_words=[], min_df = 1)
word_count = count_vec_1_grams.fit_transform(documents)
word_list = count_vec_1_grams.get_feature_names()
print "Word list = ", word_list
print "text_1 is described with", [word_list[n] + "(" + str(word_count[0,n]) + ")" for n in word_count[0].indices]

Word list =  [u'data', u'hard', u'is', u'love', u'science', u'we']
text_1 is described with [u'we(1)', u'love(1)', u'data(1)', u'science(1)']


In [70]:
# this is with bigrams
count_vec_1_grams = CountVectorizer(ngram_range=(2,2))
word_count = count_vec_1_grams.fit_transform(documents)
word_list = count_vec_1_grams.get_feature_names()
print "Word list = ", word_list
print "text_1 is described with ", [word_list[n] + "(" + str(word_count[0,n]) + ")" for n in word_count[0].indices]

Word list =  [u'data science', u'is hard', u'love data', u'science is', u'we love']
text_1 is described with  [u'we love(1)', u'love data(1)', u'data science(1)']


In [71]:
# now in uni and bigram
count_vec_1_grams = CountVectorizer(ngram_range=(1,2))
word_count = count_vec_1_grams.fit_transform(documents)
word_list = count_vec_1_grams.get_feature_names()
print "Word list = ", word_list
print "text_1 is described with ", [word_list[n] + "(" + str(word_count[0,n]) + ")" for n in word_count[0].indices]

Word list =  [u'data', u'data science', u'hard', u'is', u'is hard', u'love', u'love data', u'science', u'science is', u'we', u'we love']
text_1 is described with  [u'we(1)', u'love(1)', u'data(1)', u'science(1)', u'we love(1)', u'love data(1)', u'data science(1)']


In [72]:
# hashing to help when ngrams get to large
from sklearn.feature_extraction.text import HashingVectorizer
hash_vect = HashingVectorizer(n_features = 1000)
word_hashed = hash_vect.fit_transform(twenty_sci_news.data)
word_hashed.shape

(1187, 1000)

## Data Processing With Numpy

In [75]:
import numpy as np

In [77]:
list_of_ints = [1,2,3]
Array_1 = np.array(list_of_ints)
Array_1[1] # access same as a list

2

In [78]:
print type(Array_1)
print Array_1.dtype

<type 'numpy.ndarray'>
int32


In [82]:
print "This array takes up" ,Array_1.nbytes, "bytes"

This array takes up 12 bytes


In [83]:
# to save memory ints can be made smaller
Array_1 = np.array(list_of_ints, dtype='int8')

In [84]:
# change the data type
Array_1b = Array_1.astype('float32')
Array_1b

array([ 1.,  2.,  3.], dtype=float32)

In [88]:
# heterogenous lists
complex_list = [1,2,3] + [1.,2.,3.] + ['a', 'b', 'c']
Array_2 = np.array(complex_list[:3])
print 'complex_list[:3]', Array_2.dtype
Array_2 = np.array(complex_list[:6]) # then it is ints and floats
print "complex_list[:6]", Array_2.dtype
Array_2 = np.array(complex_list[:]) # finally adding strings
print "complex_list[:]", Array_2.dtype

complex_list[:3] int32
complex_list[:6] float64
complex_list[:] |S32


In [90]:
# check if the array is numeric
print isinstance(Array_2[0], np.number)

False


In [91]:
# transfomr into bidimensional array
a_list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
Array_2D = np.array(a_list_of_lists)
Array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# select by rows and columns
Array_2D[1,1]

5

In [93]:
# transform into multidimensional array ; more thant 2 dimensions
a_list_of_lists_of_lists = [[[1,2], [3,4], [5,6]], [[7,8], [9,10],[11,12]]]
Array_3D = np.array(a_list_of_lists_of_lists)
Array_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [94]:
# access by using 3 - yes 3 - indexes
Array_3D[0,2,0] 

5

## Reshaping Arrays

In [95]:
import numpy as np
original_array = np.array([1,2,3,4,5,6,7,8])
Array_a = original_array.reshape(4,2)
Array_b = original_array.reshape(4,2).copy()
Array_c = original_array.reshape(2,2,2)
# reshape creeates views and not copies, so only the unaffected one is copy()
original_array[0] = -1

In [96]:
print Array_a
print Array_b
print Array_c

[[-1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[-1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]]


In [98]:
# resizing will change actual shape
original_array.resize(4,2)
original_array.T

array([[-1,  3,  5,  7],
       [ 2,  4,  6,  8]])

In [99]:
# create array from ordinal values
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
# reverse order of array values
np.arange(9)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [102]:
# for random integers
np.random.randint(low=1,high=10,size=(3,3)).reshape(3,3)

array([[8, 5, 1],
       [6, 3, 5],
       [6, 5, 5]])

In [104]:
# zero and one matrices
print "Zeros"
print np.zeros((3,3))
print "Ones"
print np.ones((3,3))
print "Diagnoals"
print np.eye(3)

Zeros
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Ones
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Diagnoals
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [105]:
# grid search for optimal paramters? not a problem
fractions = np.linspace(start=0, stop = 1, num = 10)
fractions

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [106]:
# logatrhimic growth too
np.logspace(start=0, stop =1, num = 10, base = 10.0)

array([  1.        ,   1.29154967,   1.66810054,   2.15443469,
         2.7825594 ,   3.59381366,   4.64158883,   5.9948425 ,
         7.74263683,  10.        ])

In [107]:
# 3x3 standard gaussian
np.random.normal(size = (3,3))

array([[-0.43294648,  0.01630927, -0.69048359],
       [ 0.10102101,  0.04083076,  0.36928239],
       [ 0.46704087,  1.14339323, -0.72719884]])

In [108]:
# specifing means and std
np.random.normal(loc=1.0, scale = 3.0, size = (3,3)) # loc = mean ; scale = std

array([[ 2.93049591,  0.39677472, -3.21282723],
       [ 0.76606218,  2.87158197, -2.8629266 ],
       [-0.98926459,  4.17799848, -1.37658382]])

In [109]:
# make a uniform dist
np.random.uniform(low=0.0, high = 1.0, size= (3,3))

array([[ 0.38961073,  0.35867929,  0.69853802],
       [ 0.28265605,  0.62237905,  0.02648808],
       [ 0.98953812,  0.87585494,  0.82413957]])

## Getting Array Data Directly From a File

In [111]:
import numpy as np
hs = np.loadtxt('data\\regression-datasets-housing.csv', delimiter=',', dtype=float)

In [112]:
# or just use pandas
hs = pd.read_csv('data\\regression-datasets-housing.csv', header = None)

In [113]:
# use values to extract an array 
hs_array = hs.values
hs_array.dtype

dtype('float64')

In [115]:
# apply mathematical operations to scalar to be performed elementwise
a = np.arange(5).reshape(1,5)
a += 1

In [116]:
a * a

array([[ 1,  4,  9, 16, 25]])

In [117]:
# obtain elementwise opreations without restructing data
# broadcasting
a = np.arange(5).reshape(1,5) + 1
b = np.arange(5).reshape(5,1) + 1
a * b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [120]:
# this is equivalent to
a2 = np.array([1,2,3,4,5] * 5).reshape(5,5)
a2 * a2.T

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [124]:
# sum via  the axis
print np.sum(a2, axis = 0) # sum by column
print np.sum(a2, axis = 1) # sum by row

[ 5 10 15 20 25]
[15 15 15 15 15]


In [126]:
# arrays are fast
# compare list speed to array speed
%timeit -n 1 -r 3 np.arange(10**6) + 1.0 # -n 1  for one loop ; -r 3 for 3 executions

1 loops, best of 3: 4.54 ms per loop


In [127]:
%timeit -n 1 -r 3 [i+1.0 for i in range(10**6)]

1 loops, best of 3: 92 ms per loop


In [129]:
# this can also be show on math operations
import math
%timeit -n 1 -r 3 [math.sqrt(i) for i in range(10**6)]

1 loops, best of 3: 159 ms per loop


In [130]:
%timeit -n 1 -r 3 np.sqrt(np.arange(10**6))

1 loops, best of 3: 5.91 ms per loop


## Marix Opretaions - pg 75

In [2]:
import numpy as np
# matrix * matrix 
M = np.arange(5*5, dtype = float).reshape(5,5)
M

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [3]:
coefs = np.array([1., .5, .5, .5, .5])
coefs_matrix = np.column_stack((coefs, coefs[::-1]))
coefs_matrix

array([[ 1. ,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  1. ]])

In [5]:
np.dot(M, coefs)

array([  5.,  20.,  35.,  50.,  65.])

In [6]:
# mutiply the array by stack coeffecient vectors
np.dot(M, coefs_matrix)

array([[  5.,   7.],
       [ 20.,  22.],
       [ 35.,  37.],
       [ 50.,  52.],
       [ 65.,  67.]])

In [7]:
# slicing and indexing
M = np.arange(10 * 10 , dtype = int).reshape(10,10)

In [8]:
# extract even rows from 2 to 8
M[2:9:2, : ]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [9]:
# select the 5th column
M[2:9:2, 5:]

array([[25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49],
       [65, 66, 67, 68, 69],
       [85, 86, 87, 88, 89]])

In [10]:
# start from column 5 but in reverse order the index 0
M[2:9:2, 5::-1]

array([[25, 24, 23, 22, 21, 20],
       [45, 44, 43, 42, 41, 40],
       [65, 64, 63, 62, 61, 60],
       [85, 84, 83, 82, 81, 80]])

In [12]:
# create mask to select rows
row_index = (M[:,0] >= 20) & (M[:,0] <= 80)
col_index = M[0,:] >= 5
M[row_index, :][:,col_index]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89]])

In [13]:
# provide row or column index to select from array
row_index = [1,1,2,7]
col_index = [0,2,4,8]
# apply to select 
M[row_index, col_index]

array([10, 12, 24, 78])

In [15]:
# select BETWEEN these sections
M[row_index,: ][:, col_index]

array([[10, 12, 14, 18],
       [10, 12, 14, 18],
       [20, 22, 24, 28],
       [70, 72, 74, 78]])

In [18]:
# if a new data needs to be created you must use copy
N = M[2:9:2, 5:].copy()
N

array([[25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49],
       [65, 66, 67, 68, 69],
       [85, 86, 87, 88, 89]])

## Stacking Numpy Arrays

In [19]:
import numpy as np
d = np.arange(10*5).reshape(10,5)
single = np.arange(1*5).reshape(1,5)
lines = np.arange(3*5).reshape(3,5)

In [23]:
# stacking a single line
np.vstack((d, single))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4]])

In [24]:
# stacking many
np.vstack((d, lines))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
# add bias unit horzontially
bias = np.ones(10).reshape(10,1)
np.hstack((d, bias))

array([[  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.],
       [ 25.,  26.,  27.,  28.,  29.,   1.],
       [ 30.,  31.,  32.,  33.,  34.,   1.],
       [ 35.,  36.,  37.,  38.,  39.,   1.],
       [ 40.,  41.,  42.,  43.,  44.,   1.],
       [ 45.,  46.,  47.,  48.,  49.,   1.]])

In [28]:
# column stack does not require the reshape
bias = np.ones(10)
np.column_stack((d, bias))

array([[  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.],
       [ 25.,  26.,  27.,  28.,  29.,   1.],
       [ 30.,  31.,  32.,  33.,  34.,   1.],
       [ 35.,  36.,  37.,  38.,  39.,   1.],
       [ 40.,  41.,  42.,  43.,  44.,   1.],
       [ 45.,  46.,  47.,  48.,  49.,   1.]])

In [30]:
# opearating on 3 Dimensional structure
np.dstack((d*1, d*2, d*3)).T

array([[[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
        [  1,   6,  11,  16,  21,  26,  31,  36,  41,  46],
        [  2,   7,  12,  17,  22,  27,  32,  37,  42,  47],
        [  3,   8,  13,  18,  23,  28,  33,  38,  43,  48],
        [  4,   9,  14,  19,  24,  29,  34,  39,  44,  49]],

       [[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
        [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98]],

       [[  0,  15,  30,  45,  60,  75,  90, 105, 120, 135],
        [  3,  18,  33,  48,  63,  78,  93, 108, 123, 138],
        [  6,  21,  36,  51,  66,  81,  96, 111, 126, 141],
        [  9,  24,  39,  54,  69,  84,  99, 114, 129, 144],
        [ 12,  27,  42,  57,  72,  87, 102, 117, 132, 147]]])

In [31]:
# inesert values into an array
np.insert(d, 3, bias, axis = 1)

array([[ 0,  1,  2,  1,  3,  4],
       [ 5,  6,  7,  1,  8,  9],
       [10, 11, 12,  1, 13, 14],
       [15, 16, 17,  1, 18, 19],
       [20, 21, 22,  1, 23, 24],
       [25, 26, 27,  1, 28, 29],
       [30, 31, 32,  1, 33, 34],
       [35, 36, 37,  1, 38, 39],
       [40, 41, 42,  1, 43, 44],
       [45, 46, 47,  1, 48, 49]])

In [33]:
# to insernt one array into another one must be transposed
np.insert(d,3,d.T, axis = 1)

array([[ 0,  1,  2,  0,  1,  2,  3,  4,  3,  4],
       [ 5,  6,  7,  5,  6,  7,  8,  9,  8,  9],
       [10, 11, 12, 10, 11, 12, 13, 14, 13, 14],
       [15, 16, 17, 15, 16, 17, 18, 19, 18, 19],
       [20, 21, 22, 20, 21, 22, 23, 24, 23, 24],
       [25, 26, 27, 25, 26, 27, 28, 29, 28, 29],
       [30, 31, 32, 30, 31, 32, 33, 34, 33, 34],
       [35, 36, 37, 35, 36, 37, 38, 39, 38, 39],
       [40, 41, 42, 40, 41, 42, 43, 44, 43, 44],
       [45, 46, 47, 45, 46, 47, 48, 49, 48, 49]])

In [55]:
# axis can be changed for instert 
np.insert(d,3,bias.reshape(2,5)[1], axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 1,  1,  1,  1,  1],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])